import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const monaSans = localFont({
  src: "../fonts/Mona-Sans.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${monaSans.className} antialiased bg-[#fbfbfb] min-h-screen flex place-content-center md:pt-36 pt-10`}
      >
        <section className="max-w-2xl w-full">{children}</section>
      </body>
    </html>
  );
}
